name: TEST
on:
  push: 
    branches: [ "master" ]

jobs: 
  build: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run ls Command
        run: ls
      - name: Cd into Client
        run: cd ECommerce-Website/client
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version:  16
          cache: 'npm'
      - run: npm install --legacy-peer-deps
      - name: Test 
        run: npm test