name: TEST
on:
  push: 
    branches: [ "master" ]

jobs: 
  test: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version:  16
      
      - name: install packages for client
        run: npm install --legacy-peer-deps
        working-directory: ECommerce-Website/client
      
      - name: Test Client 
        continue-on-error: true
        run: npm test
        working-directory: ECommerce-Website/client

      - name: install packages for server
        run: npm install --legacy-peer-deps
        working-directory: ECommerce-Website/server
      
      - name: Test Server
        continue-on-error: true
        run: npm test
        working-directory: ECommerce-Website/server
  
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to AWS ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY }}

      - name: Build Client Docker image
        run: docker build -t ${{ secrets.ECR_REPOSITORY }}/client:latest .
        working-directory: ECommerce-Website/client

      - name: Push Client Docker image
        run: docker push ${{ secrets.ECR_REPOSITORY }}/client:latest
        working-directory: ECommerce-Website/client  
  
      - name: Build Server Docker image
        run: docker build -t ${{ secrets.ECR_REPOSITORY }}/server:latest .
        working-directory: ECommerce-Website/server

      - name: Push Server Docker image
        run: docker push ${{ secrets.ECR_REPOSITORY }}/server:latest
        working-directory: ECommerce-Website/server  